//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Remainder { get; set; }
        public string Priority { get; set; }
        public string Color { get; set; }
        public int NotebookId { get; set; }
    
        public virtual Notebook Notebooks { get; set; }
    }
}
